'use client';
import geography from '../data/map.json';
import {useEffect,useState} from 'react';
import {ENSEMBLE_SOURCE,HISTORY_SOURCE,outlookUsable,type OutlookResponse,type Spread} from '../lib/outlook';
const number=(value:number|null|undefined)=>value==null?'Unavailable':value.toFixed(1);
const range=(value:Spread|null|undefined,unit:string)=>value?`${value.median.toFixed(1)} ${unit} (range ${value.p10.toFixed(1)}–${value.p90.toFixed(1)})`:'Unavailable';
const sourceProps={target:'_blank',rel:'noreferrer'};

export default function DroughtOutlook({selected,onSelect,view}:{selected:string;onSelect:(id:string)=>void;view:'map'|'outlook'}){
  const [days,setDays]=useState(7),[data,setData]=useState<OutlookResponse|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[now,setNow]=useState<Date|null>(null);
  useEffect(()=>{
    const controller=new AbortController(),timer=setInterval(()=>setNow(new Date()),60000);
    void(async()=>{
      try{const response=await fetch('/api/outlook',{signal:controller.signal});if(!response.ok)throw new Error('The public outlook service is unavailable.');const value:OutlookResponse=await response.json();if(!outlookUsable(value))throw new Error('The outlook has expired.');if(!controller.signal.aborted){setData(value);setNow(new Date());}}
      catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Outlook unavailable.');}
      finally{if(!controller.signal.aborted)setLoading(false);}
    })();
    return()=>{controller.abort();clearInterval(timer);};
  },[attempt]);
  const usable=data&&now&&outlookUsable(data,now)?data:null;
  const region=usable?.regions.find(r=>r.id===selected),horizon=region?.horizons[days-1],recent=region?.recent;
  const recentPeak=Math.max(1,recent?.precipitation??0,recent?.normal??0);
  return <section className='drought-outlook' aria-label='Weather outlook and rainfall context'>
    <div id='outlook-view' role='tabpanel' aria-labelledby='outlook-tab' hidden={view!=='outlook'}>
    <div className='section-heading'><div><span className='eyebrow'>RAINFALL & TEMPERATURE OUTLOOK</span><h2>Choose your forecast horizon</h2></div><button className='municipality-open' disabled={loading} onClick={()=>{setLoading(true);setError(null);setAttempt(a=>a+1);}}>{loading?'Loading public outlook…':'Refresh outlook'}</button></div>
    <label className='outlook-region'>District<select value={selected} onChange={e=>onSelect(e.target.value)}>{geography.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
    <label className='timeline-label' htmlFor='forecast-horizon'>Next <strong>{days} {days===1?'day':'days'}</strong> · cumulative period starting tomorrow</label>
    <input id='forecast-horizon' type='range' min='1' max='30' step='1' value={days} onChange={e=>setDays(Number(e.target.value))} aria-valuetext={`Next ${days} days`}/>
    <div className='timeline-ticks'>{[1,7,14,21,30].map(d=><button key={d} onClick={()=>setDays(d)} aria-pressed={days===d}>{d} {d===1?'day':'days'}</button>)}</div>
    <p className='outlook-period'>{usable&&horizon?`${usable.start} to ${horizon.end} · Europe/Belgrade`:'Forecast dates unavailable until the outlook loads.'} {days>14?'Extended-range outlook: use for broad planning, not day-specific irrigation or restrictions.':'Ensemble outlook: individual daily outcomes remain uncertain.'}</p>
    <p>GFS ensemble, approximately 50 km · one representative location per district. Values show the median and 10th–90th percentile range across 31 model members, not a calibrated probability or municipal forecast. <a href={ENSEMBLE_SOURCE} {...sourceProps}>Open-Meteo / NOAA GFS</a></p>
    {(error||data&&!usable||usable?.warning)&&<p className='notice' role='status'>{error||(data&&!usable?'Outlook expired. Refresh for current data.':usable?.warning)}{error&&usable?' Showing a previous, unexpired outlook.':''}</p>}
    <div className='outlook-cards' aria-live='polite'><article><span className='eyebrow'>{region?.name??'SELECTED DISTRICT'} · POINT PROXY</span><h3>Forecast precipitation</h3><strong>{horizon?.precipitation?number(horizon.precipitation.median)+' mm':'Unavailable'}</strong><p className='uncertainty'>10th–90th percentile: {horizon?.precipitation?`${number(horizon.precipitation.p10)}–${number(horizon.precipitation.p90)} mm`:'Unavailable'}</p><p>Total across the selected {days}-day period.</p></article><article><span className='eyebrow'>AIR TEMPERATURE · 2 METRES</span><h3>Forecast temperature</h3><strong>{horizon?.temperature?number(horizon.temperature.median)+' °C':'Unavailable'}</strong><p className='uncertainty'>10th–90th percentile: {horizon?.temperature?`${number(horizon.temperature.p10)}–${number(horizon.temperature.p90)} °C`:'Unavailable'}</p><p>Mean across the selected period, not the highest daily temperature. Heat already influences the seven-day ET₀ calculation; it is not counted twice as an extra score weight.</p></article></div>
    <p className='municipality-warning'>The separate map tab shows a <strong>seven-day weather-pressure indicator</strong>. This timeline changes the ensemble outlook only. A 30-day drought classification or restriction recommendation cannot be supported by this prototype.</p>
    <details className='comparison-disclosure'><summary>Compare all districts · selected forecast horizon</summary>
    <div className='outlook-table-wrap'><table className='outlook-table'><caption>Point proxies, not district-area averages. Select a district to update the map and detail cards.</caption><thead><tr><th scope='col'>District</th><th scope='col'>Precipitation · mm<br/>median (10–90% range)</th><th scope='col'>Mean temperature · °C<br/>median (10–90% range)</th></tr></thead><tbody>{usable?.regions.map(r=>{const h=r.horizons[days-1];return <tr key={r.id} className={selected===r.id?'active-region':''}><th scope='row'><button onClick={()=>onSelect(r.id)} aria-pressed={selected===r.id}>{r.name}</button></th><td>{range(h.precipitation,'')}</td><td>{range(h.temperature,'')}</td></tr>;})??<tr><td colSpan={3}>{loading?'Retrieving real public forecasts…':'Forecast comparison unavailable.'}</td></tr>}</tbody></table></div>
    </details></div>
    <section className='rainfall-comparison' aria-label='Recent rainfall comparison'>
    <div className='section-heading'><div><span className='eyebrow'>RECENT RAINFALL · DISTRICT POINT PROXY</span><h2>{geography.find(r=>r.id===selected)?.name}: rainfall vs normal</h2></div>{view==='map'&&<button className='municipality-open' disabled={loading} onClick={()=>{setLoading(true);setError(null);setAttempt(a=>a+1);}}>{loading?'Loading rainfall…':'Refresh rainfall'}</button>}</div>
    {view==='map'&&(error||data&&!usable)&&<p className='notice' role='status'>{error??'Outlook expired. Refresh for current rainfall context.'}{error&&usable?' Showing previous, unexpired data.':''}</p>}
    <p>{recent?recent.start+' to '+recent.end:'Latest complete 30-day period'} · <strong>{recent?.percentOfNormal!=null?number(recent.percentOfNormal)+'% of normal':'Comparison unavailable'}</strong></p>
    <div className='rainfall-bars'>{[{label:'Recent rainfall',value:recent?.precipitation},{label:'1991–2020 normal',value:recent?.normal}].map((bar,i)=><div className='rainfall-bar-row' key={bar.label}><span>{bar.label}</span><div className='rainfall-track'>{bar.value!=null&&<div className={'rainfall-fill '+(i?'normal':'')} style={{width:bar.value/recentPeak*100+'%'}}/>}</div><strong>{bar.value!=null?number(bar.value)+' mm':'Unavailable'}</strong></div>)}</div>
    <p className='small-muted'>Modelled rainfall, approximately 25 km grid; delayed by at least five days. <a href={HISTORY_SOURCE} {...sourceProps}>Open-Meteo / Copernicus ERA5</a>{usable&&' · Retrieved '+new Date(usable.retrievedAt).toLocaleString('en-GB',{timeZone:'Europe/Belgrade'})+' (Europe/Belgrade)'}</p><p className='rainfall-note'>Recent dryness and low forecast stress can coexist: this comparison describes the past, while the map describes the next seven days. It is district context, not a municipal measurement.</p>
    <details className='comparison-disclosure'><summary>Compare all districts & rainfall sources</summary>
    <p>{recent?`${recent.start} to ${recent.end}`:'Recent 30-day period'} · ERA5 reanalysis, latest complete common 30-day window, ending at least five days before today because the dataset is delayed. The exact dates above identify the delay. This is modelled recent rainfall, not today’s rain gauge readings. Normal = 1991–2020 mean for the same calendar dates at the same grid location. <a href={HISTORY_SOURCE} {...sourceProps}>Open-Meteo / Copernicus ERA5</a></p>
    <div className='outlook-table-wrap'><table className='outlook-table'><caption>Approximately 25 km grid; one point proxy per district. 100% means equal to normal. This comparison does not change when the future timeline moves.</caption><thead><tr><th scope='col'>District</th><th scope='col'>Recent rain<br/>mm</th><th scope='col'>1991–2020 normal<br/>mm</th><th scope='col'>% of normal</th><th scope='col'>Recent mean<br/>temperature °C</th></tr></thead><tbody>{usable?.regions.map(r=><tr key={r.id} className={selected===r.id?'active-region':''}><th scope='row'><button onClick={()=>onSelect(r.id)}>{r.name}</button></th><td>{number(r.recent.precipitation)}</td><td>{number(r.recent.normal)}</td><td>{number(r.recent.percentOfNormal)}{r.recent.percentOfNormal!==null?'%':''}</td><td>{number(r.recent.temperature)}</td></tr>)??<tr><td colSpan={5}>{loading?'Retrieving recent rainfall…':'Recent rainfall comparison unavailable.'}</td></tr>}</tbody></table></div>
    {usable?.regions.some(r=>r.recent.reason)&&<p role='status'>Some recent rainfall comparisons are unavailable: a complete 30-day series and matching historical grid are required.</p>}
    </details></section>
    <details className='reservoir-status'><summary>Water supply data · reservoir and groundwater levels unavailable</summary><span className='eyebrow'>WATER SUPPLY CONTEXT · ALL SEVEN DISTRICTS</span><h3>Reservoir levels unavailable</h3><p>No reliable, current public reservoir-level or usable-storage feed linked to these districts has been verified. Reservoir storage is therefore not included in the score. River gauge heights and Danube discharge are not substitutes for reservoir storage.</p><p>Before acting, obtain dated reservoir levels, usable capacity and district supply connections from the water authority. Even a low weather-pressure score does not establish sufficient water supply.</p><p><a href='https://www.vodevojvodine.com/osnovni-podaci/' {...sourceProps}>Vode Vojvodine — responsible authority</a> · <a href='https://www.vodevojvodine.com/bilteni/' {...sourceProps}>Public bulletins</a> · <a href='https://www.hidmet.gov.rs/latin/hidrologija/naslovna_stanje.php' {...sourceProps}>RHMZ hydrological monitoring</a></p></details>
    <details className='municipality-method'><summary>Dates, sampling and uncertainty</summary><p>{usable?`Outlook retrieved ${new Date(usable.retrievedAt).toLocaleString('en-GB',{timeZone:'Europe/Belgrade'})} Europe/Belgrade.`:'No current retrieval available.'} Retrieval is not model issue time. Each percentile is calculated after summing precipitation or averaging temperature within each complete member across the chosen horizon. Incomplete variables are withheld; no missing day becomes zero.</p><p>The baseline uses 30 years, except 29 February (eight leap years). It is a derived ERA5 climatology, not an official Serbian station normal. The sampling point nearest each district’s area-weighted sample centre is used; spatial variation inside a district is unresolved. Separate districts may share an ensemble grid cell. GFS and ERA5 use different models and resolutions; the historical comparison uses ERA5 on both sides, not GFS against ERA5.</p><p>Forecasts are not bias-corrected or calibrated locally. Ensemble spread omits some model uncertainty, particularly at longer horizons. Temperature, reservoir availability and recent rainfall support authority review; only forecast rainfall and ET₀ enter the existing seven-day score.</p><p><a href='/api/outlook' {...sourceProps}>Outlook data and requested/returned coordinates</a> · <a href='https://open-meteo.com/en/terms' {...sourceProps}>Data terms</a></p></details>
  </section>;
}
